'use client';
import { useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { ArrowUpRight, Mail } from 'lucide-react';
import Link from '@/components/link';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
const topics=['General Enquiry','Product Enquiry','Partnership','Research Collaboration','Business Collaboration','Media','Career Opportunity','Other'];
export function ContactForm(){const params=useSearchParams();const [chosenTopic,setTopic]=useState<string|null>(null);const topic=chosenTopic||(topics.includes(params.get('topic')||'')?params.get('topic')!:'General Enquiry');const [draft,setDraft]=useState('');const product=params.get('product')==='learn'?'AVEERANEX Learn':params.get('product')==='techfm'?'TechFM':'';
function submit(e:React.SubmitEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const value=(key:string)=>{const v=d.get(key);return typeof v==='string'?v:'';};const body=`Full name: ${value('name')}\nEmail: ${value('email')}\nOrganization: ${value('organization')||'Not specified'}\nTopic: ${topic}${product?' — '+product:''}\n\n${value('message')}`;setDraft(`mailto:Info@aveeranex.com?subject=${encodeURIComponent(topic+(product?' — '+product:''))}&body=${encodeURIComponent(body)}`);}
return <form className="contact-form" onSubmit={submit} onChange={()=>setDraft('')}><div className="form-heading"><h3>Tell us what you have in mind.</h3><span>Fields marked * are required</span></div><div className="form-row"><label>Full name *<input name="name" autoComplete="name" placeholder="Your full name" required maxLength={100}/></label><label>Email address *<input name="email" type="email" autoComplete="email" placeholder="you@company.com" required maxLength={200}/></label></div><label>Organization<input name="organization" autoComplete="organization" placeholder="Company or organization (optional)" maxLength={150}/></label><label htmlFor="enquiry-topic">I am contacting AVEERANEX about</label><Select value={topic} onValueChange={v=>{if(v)setTopic(v);setDraft('');}}><SelectTrigger id="enquiry-topic" className="topic-select"><SelectValue/></SelectTrigger><SelectContent>{topics.map(t=><SelectItem value={t} key={t}>{t}</SelectItem>)}</SelectContent></Select>{product&&<p className="selected-product">Product interest: {product}</p>}<label>Message *<textarea name="message" placeholder="Share your idea, question or opportunity…" required rows={5} maxLength={3000}/></label><p className="form-note">Your message is prepared here, then sent using your email app. We don’t store your form entries on this website. <Link href="/privacy">Privacy policy ↗</Link></p><button type="submit" className="button">Prepare message <ArrowUpRight size={17}/></button>{draft&&<output className="form-result"><Mail size={23}/><div><strong>Your message is ready to send.</strong><p>Open your email app, review the draft and press send. Nothing has been sent yet.</p><a href={draft} className="text-link">Open email draft <ArrowUpRight size={16}/></a></div></output>}</form>;}
