'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, ArrowLeft, Check, Code2, Sparkles, AudioLines, Play, Layers3, BrainCircuit, ChartNoAxesCombined, Globe2, Zap, Network } from 'lucide-react';
import { Progress } from '@/components/ui/progress';

export function Reveal({children,className=''}:{children:React.ReactNode,className?:string}) { const ref=useRef<HTMLDivElement>(null); useEffect(()=>{const el=ref.current;if(!el)return;const obs=new IntersectionObserver(([e])=>{if(e.isIntersecting){el.classList.add('is-visible');obs.unobserve(el);}},{threshold:.08});obs.observe(el);return()=>obs.disconnect();},[]);return <div ref={ref} className={`reveal ${className}`}>{children}</div>; }
export function LearnMockup(){const [lesson,setLesson]=useState(1);const lessons=['Explore the dataset','Train your first model','Evaluate the results'];return <div className="mockup learn-mock"><div className="mock-top"><span><Layers3 size={16}/> AVEERANEX <b>LEARN</b></span><small>PRODUCT CONCEPT</small><span className="avatar">A</span></div><div className="learn-content"><div className="mock-sidebar"><span className="mock-label">YOUR LEARNING PATH</span>{['01','02','03'].map((n,i)=><button key={n} className={lesson===i?'lesson active':'lesson'} onClick={()=>setLesson(i)}><span>{i<lesson?<Check size={12}/>:n}</span>{lessons[i]}</button>)}<div className="mock-progress"><span>Learning in motion</span><Progress value={(lesson+1)*33} aria-label="Illustrative lesson progress"/><small>{lesson+1} of 3 concept lessons</small></div></div><div className="mock-work"><span className="mock-label">MACHINE LEARNING / LAB 01</span><h4>{lessons[lesson]}<span className="blue">.</span></h4><p>{['Every insight starts with a question.','Turn your understanding into action.','See the story behind your model.'][lesson]}</p><div className="code-window"><span><i/> experiment.py <Code2 size={12}/></span><pre><em>from</em> sklearn <em>import</em> datasets<br/><br/><span className="code-comment"># Learn. Experiment. Understand.</span><br/>data = datasets.load_iris()<br/>model.<b>fit</b>(data, target)<br/><br/><span className="code-comment">↳ Your next discovery starts here.</span></pre></div><div className="tutor"><Sparkles size={16}/><div><strong>Your AI learning companion</strong><p>Explore the why behind every line.</p></div><span>↗</span></div></div></div><div className="mock-foot"><i/> LEARN BY DOING <span>Illustrative interface · In development</span></div></div>;}
export function TechMockup(){return <div className="mockup tech-mock"><div className="mock-top"><span><AudioLines size={19}/> TECH<span className="orange">FM</span></span><small>PRODUCT CONCEPT</small><span className="signal">●</span></div><div className="tech-content"><div className="tech-kicker">YOUR SIGNAL IN THE NOISE</div><h4>Stay ahead.<br/>Listen intelligently.</h4><div className="waveform" aria-hidden="true">{Array.from({length:51},(_,i)=><i key={i} style={{height:`${14+Math.abs(Math.sin(i*1.9)*Math.cos(i*.4))*58}px`,animationDelay:`${i*.05}s`}}/>)}</div><div className="episode"><div className="episode-icon"><AudioLines size={25}/></div><div><span className="mock-label">THE INTELLIGENCE BRIEF</span><strong>The next chapter of artificial intelligence</strong><small>AI & innovation · Concept episode</small></div><span className="play-icon"><Play size={12}/></span></div><div className="summary"><span><Sparkles size={13}/> THE ESSENTIAL INSIGHT</span><p>From emerging ideas to meaningful context. Understand the developments shaping what comes next.</p></div><div className="topic-tags"><span>Artificial intelligence</span><span>Semiconductors</span><span>Global innovation</span></div></div><div className="mock-foot"><i/> LESS NOISE. MORE INTELLIGENCE.<span>Illustrative interface</span></div></div>;}
const products=[{id:'learn',name:'AVEERANEX Learn',number:'01',category:'AI + INTERACTIVE LEARNING',title:<>Learn by<br/>doing<span className="blue">.</span></>,description:'An interactive learning platform that turns complex technology concepts into practical, hands-on experiences.',topics:['Statistics','Data analytics','Machine learning','Generative AI'],cta:'Explore AVEERANEX Learn'},{id:'techfm',name:'TechFM',number:'02',category:'AI + TECHNOLOGY INTELLIGENCE',title:<>Understand<br/>technology. Faster<span className="orange">.</span></>,description:'AI-powered intelligence from global podcasts, technology news and innovation ecosystems. Turn hours of information into useful insights.',topics:['Podcasts','AI summaries','Technology news','Market trends'],cta:'Discover TechFM'}];
export function ProductShowcase(){const [index,setIndex]=useState(0);const p=products[index];return <section className="section showcase"><div className="section-head"><div><span className="eyebrow">02 / What we are building</span><h2>One company.<br/>Multiple intelligent products.</h2></div><Link className="text-link" href="/products">Meet our products <ArrowUpRight size={17}/></Link></div><div className={`product-panel ${index===1?'tech-panel':''}`}><div className="product-copy"><div className="product-title"><span>{p.name}</span><span className="status">Coming soon</span></div><span className="eyebrow">{p.category}</span><h3>{p.title}</h3><p className="body-copy">{p.description}</p><div className="topic-tags">{p.topics.map(t=><span key={t}>{t}</span>)}</div><Link href={`/products#${p.id}`} className="text-link">{p.cta}<ArrowUpRight size={17}/></Link></div><div className="product-graphic">{index===0?<LearnMockup/>:<TechMockup/>}</div></div><div className="showcase-control"><span className="mono">{p.number} <span>/ 02</span></span><div className="showcase-track"><span style={{transform:`translateX(${index*100}%)`}}/></div><div><button aria-label="Previous product" onClick={()=>setIndex(index===0?1:0)}><ArrowLeft size={18}/></button><button aria-label="Next product" onClick={()=>setIndex(index===0?1:0)}><ArrowRight size={18}/></button></div></div></section>;}
const orbitItems=[['LEARN','Interactive experiences that turn knowledge into capability.'],['TECHFM','Technology intelligence that brings the signal into focus.'],['AI','Context-aware systems at the heart of every experience.'],['ANALYTICS','Meaningful patterns that turn data into understanding.'],['AUTOMATION','Intelligent workflows that make room for what matters.'],['FUTURE PRODUCTS','New possibilities across intelligent digital experiences.']];
export function Ecosystem(){const [selected,setSelected]=useState(0);return <section className="section ecosystem"><div><span className="eyebrow">03 / Connected by intelligence</span><h2>The AVEERANEX<br/>intelligence ecosystem<span className="blue">.</span></h2><p className="body-copy">One technology vision powering multiple intelligent digital experiences.</p><div className="orbit-detail" aria-live="polite"><span className="eyebrow">{orbitItems[selected][0]}</span><p>{orbitItems[selected][1]}</p></div></div><div className="ecosystem-diagram"><div className="ecosystem-ring ring-a"/><div className="ecosystem-ring ring-b"/><div className="ecosystem-ring ring-c"/><div className="ecosystem-center"><span>Λ</span><b>AVEERANEX</b></div>{orbitItems.map(([name],i)=><button key={name} className={`ecosystem-node node-${i} ${selected===i?'selected':''}`} onFocus={()=>setSelected(i)} onMouseEnter={()=>setSelected(i)} onClick={()=>setSelected(i)} aria-pressed={selected===i}><i/>{name}</button>)}</div></section>;}
export function Process({about=false}:{about?:boolean}) {const stages=about?['Research','Prototype','Intelligence','Validation','Product','Scale']:['Discover','Understand','Interact','Apply'];return <section className="section process"><div className="section-head"><div><span className="eyebrow">{about?'How we build':'04 / What drives us'}</span><h2>{about?<>From the first question.<br/>To the next possibility.</>:<>From information<br/>to intelligence.</>}</h2></div><p className="body-copy">{about?'Our ideas move through a cycle of exploration, experimentation and validation. Every step brings the experience closer to the people it serves.':'Our products reduce complexity and transform information into meaningful, usable experiences.'}</p></div><div className={`process-stages ${about?'six-stages':''}`}>{stages.map((s,i)=><div className="process-stage" key={s}><span className="mono">0{i+1}</span><div className={`process-symbol symbol-${i%4}`} aria-hidden="true">{[Globe2,Network,Sparkles,ChartNoAxesCombined,Layers3,Zap].map((Icon,j)=>j===i?<Icon key={j} size={42} strokeWidth={1}/>:null)}<div className="symbol-grid"/></div><h3>{s}<ArrowRight size={17}/></h3><p>{(about?['Explore the real problem.','Make the idea tangible.','Build meaningful context.','Test, learn and improve.','Create an intuitive experience.','Grow with purpose.']:['Find the signal in the noise.','Connect ideas to meaning.','Make knowledge an experience.','Turn understanding into action.'])[i]}</p></div>)}</div></section>;}
export function Capabilities(){const names=['Artificial intelligence','Machine learning','Generative AI','Agentic systems','Data analytics','Interactive learning','Technology intelligence','Automation','Digital platforms'];return <section className="section capabilities"><span className="eyebrow">05 / Powered by possibility</span><div className="section-head"><h2>The technologies<br/>behind the experience.</h2><p className="body-copy">A connected foundation.<br/>Designed around human potential.</p></div><div className="capabilities-grid">{names.map((name,i)=><div key={name}><span className="mono">0{i+1}</span><h3>{name}</h3><ArrowUpRight size={20}/></div>)}</div></section>;}
export function Philosophy() {
  return (
    <section className="section philosophy">
      <span className="eyebrow">06 / Our product philosophy</span>
      <div className="philosophy-grid">
        {[
          ['Intelligence', 'without complexity.'],
          ['Technology', 'without friction.'],
          ['Learning', 'without limits.']
        ].map(([a, b], i) => (
          <Reveal key={a}>
            <span className="mono">0{i + 1}</span>
            <h2>
              {a}<br />
              <span>{b}</span>
            </h2>
            <span className="philosophy-star">✳</span>
          </Reveal>
        ))}
      </div>
    </section>
  );
}
export function Future(){return <section className="section future"><div><span className="eyebrow">07 / Exploring next</span><h2>What comes next?<br/>We’re already asking.</h2><p className="body-copy">We continuously explore opportunities where technology can simplify real-world experiences.</p></div><div className="future-concept"><div className="future-glyph" aria-hidden="true"><Layers3 size={68} strokeWidth={.7}/><span>+</span><BrainCircuit size={55} strokeWidth={.8}/></div><span className="status">Research stage</span><h3>Intelligent digital marketplaces</h3><p>Exploring platforms that connect people with personalized products and services.</p></div></section>;}
export function FinalCTA(){return <section className="section final-cta"><div className="horizon" aria-hidden="true"/><span className="eyebrow"><i className="blue-dot"/> The future is taking shape</span><h2>The next intelligent experience<br/>is already being built<span className="blue">.</span></h2><div className="actions"><Link href="/products" className="button light-button">Explore our products <ArrowUpRight size={17}/></Link><Link href="/contact" className="text-link">Contact AVEERANEX <ArrowUpRight size={17}/></Link></div></section>;}
export function ProductDetails({ productId }: { productId?: 'learn' | 'techfm' | 'all' } = {}) {
  const filtered = productId && productId !== 'all' ? products.filter(p => p.id === productId) : products;
  return <>{filtered.map((p) => {
    const i = products.findIndex(item => item.id === p.id);
    return <section id={p.id} key={p.id} className={`section product-detail ${i ? 'reverse-product' : ''}`}><div className="detail-main"><div className="product-copy"><div className="product-title"><span>{p.name}</span><span className="status">In development</span></div><span className="eyebrow">{p.category}</span><h2>{p.title}</h2><p className="body-copy">{p.description}</p><div className="experience-flow">{(i ? ['Discover', 'Summarize', 'Understand', 'Listen', 'Act'] : ['Learn', 'Practice', 'Experiment', 'Build', 'Evaluate']).map((s, j) => <span key={s}>{j > 0 && <b>→</b>}{s}</span>)}</div><Link className="button" href={`/contact?topic=Product%20Enquiry&product=${p.id}`}>Enquire about {i ? 'TechFM' : 'Learn'}<ArrowUpRight size={17} /></Link><p className="release-note">Coming soon · {i ? 'techfm' : 'learn'}.aveeranex.com</p></div><div className="product-graphic">{i ? <TechMockup /> : <LearnMockup />}</div></div><div className="detail-features"><div><span className="eyebrow">{i ? 'A world of intelligence' : 'Explore what you can learn'}</span><div className="topic-tags">{(i ? ['Technology podcasts', 'Technology news', 'Global innovation', 'AI developments', 'Semiconductors', 'Market trends', 'Investments'] : ['Statistics', 'Data analytics', 'Machine learning', 'Deep learning', 'Reinforcement learning', 'Generative AI', 'Agentic AI']).map(t => <span key={t}>{t}</span>)}</div></div><div><span className="eyebrow">Designed for a better experience</span><ul>{(i ? ['Podcast discovery & speaker search', 'AI episode and voice summaries', 'Technology & AI trend monitoring', 'Semiconductor & investment intelligence', 'Source-backed insights'] : ['Interactive lessons & hands-on activities', 'Practical labs & case studies', 'AI learning assistance', 'Progress analytics & voice learning', 'Real-world datasets']).map(t => <li key={t}><Check size={14} />{t}</li>)}</ul></div></div></section>;
  })}</>;
}


